[package]
name = "htap-tpcc"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
csv = { workspace = true }
htap-common = { path = "../htap-common" }
htap-sql = { path = "../htap-sql" }
htap-catalog = { path = "../htap-catalog" }
htap-movement = { path = "../htap-movement" }
htap-server = { path = "../htap-server" }

[dev-dependencies]
anyhow = { workspace = true }
tempfile = { workspace = true }
