[package]
name = "htap-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
htap-common = { path = "../htap-common" }
htap-server = { path = "../htap-server" }
htap-sql = { path = "../htap-sql" }
htap-wire = { path = "../htap-wire" }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
rustls-pki-types = { workspace = true }

[dev-dependencies]
rcgen = "0.13"
tempfile = { workspace = true }
