//! Bounded property-based reference model tests for MVCC snapshot isolation in `Engine`.
//!
//! Properties asserted:
//! 1. Snapshot stability: reads equal the model's latest committed value at or below the snapshot.
//! 2. No future visibility: reads never expose a version above the requested snapshot.
//! 3. Delete correctness: a visible latest tombstone returns no row and does not resurrect an older put.
//! 4. First-writer-wins: two commits based on the same snapshot and same key cannot both succeed;
//!    a rejected commit leaves no value behind.
//! 5. Recovery equivalence: model and engine agree before and after reopen, including frequent flushes.

use std::collections::BTreeMap;

use htap_common::{HtapError, Row, Value, Version};
use htap_rowstore::{Engine, EngineOptions, Mutation, Snapshot};
use proptest::prelude::*;

/// Independent reference model tracking per-key versioned Put and Delete records.
#[derive(Debug, Clone)]
struct Model {
    /// Ordered history of commits per key: `(commit_version, Option<Row>)`.
    /// `Some(row)` indicates a `Put`, `None` indicates a `Delete` (tombstone).
    history: BTreeMap<Vec<u8>, Vec<(Version, Option<Row>)>>,
    /// Current visible commit version in the model.
    visible_version: Version,
}

impl Default for Model {
    fn default() -> Self {
        Self::new()
    }
}

impl Model {
    fn new() -> Self {
        Self {
            history: BTreeMap::new(),
            visible_version: Version::INITIAL,
        }
    }

    /// Highest committed version for a given key, if any.
    fn newest_version(&self, key: &[u8]) -> Option<Version> {
        self.history
            .get(key)
            .and_then(|entries| entries.last())
            .map(|(v, _)| *v)
    }

    /// Check if a commit on `key` based on `snapshot_v` would conflict with a newer committed write.
    fn has_conflict(&self, key: &[u8], snapshot_v: Version) -> bool {
        self.newest_version(key).is_some_and(|v| v > snapshot_v)
    }

    /// Apply a successful Put to the model.
    fn apply_put(&mut self, key: Vec<u8>, version: Version, row: Row) {
        self.history
            .entry(key)
            .or_default()
            .push((version, Some(row)));
        self.visible_version = version;
    }

    /// Apply a successful Delete tombstone to the model.
    fn apply_delete(&mut self, key: Vec<u8>, version: Version) {
        self.history.entry(key).or_default().push((version, None));
        self.visible_version = version;
    }

    /// Get the visible row at `snapshot_v` from the model.
    fn get_at(&self, key: &[u8], snapshot_v: Version) -> Option<Row> {
        if let Some(entries) = self.history.get(key) {
            for (v, val) in entries.iter().rev() {
                if *v <= snapshot_v {
                    return val.clone();
                }
            }
        }
        None
    }

    /// Return metadata `(version, is_tombstone)` for the entry that answered the read at `snapshot_v`.
    fn latest_entry_meta(&self, key: &[u8], snapshot_v: Version) -> Option<(Version, bool)> {
        if let Some(entries) = self.history.get(key) {
            for (v, val) in entries.iter().rev() {
                if *v <= snapshot_v {
                    return Some((*v, val.is_none()));
                }
            }
        }
        None
    }
}

/// Operations generated by proptest.
#[derive(Debug, Clone)]
enum Step {
    CaptureSnapshot,
    CommitPut {
        snap_idx: usize,
        key_idx: u8,
        val: i64,
    },
    CommitDelete {
        snap_idx: usize,
        key_idx: u8,
    },
    FirstWriterWinsRace {
        snap_idx: usize,
        key_idx: u8,
        val1: i64,
        val2: i64,
    },
    PointRead {
        snap_idx: usize,
        key_idx: u8,
    },
    Flush,
    Reopen,
}

fn any_step() -> impl Strategy<Value = Step> {
    prop_oneof![
        3 => Just(Step::CaptureSnapshot),
        8 => (any::<usize>(), 0u8..4, any::<i64>()).prop_map(|(snap_idx, key_idx, val)| {
            Step::CommitPut { snap_idx, key_idx, val }
        }),
        4 => (any::<usize>(), 0u8..4).prop_map(|(snap_idx, key_idx)| {
            Step::CommitDelete { snap_idx, key_idx }
        }),
        4 => (any::<usize>(), 0u8..4, any::<i64>(), any::<i64>()).prop_map(|(snap_idx, key_idx, val1, val2)| {
            Step::FirstWriterWinsRace { snap_idx, key_idx, val1, val2 }
        }),
        6 => (any::<usize>(), 0u8..4).prop_map(|(snap_idx, key_idx)| {
            Step::PointRead { snap_idx, key_idx }
        }),
        2 => Just(Step::Flush),
        2 => Just(Step::Reopen),
    ]
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(48))]

    #[test]
    fn prop_mvcc_engine_matches_model(steps in prop::collection::vec(any_step(), 12..35)) {
        let dir = tempfile::tempdir().unwrap();
        // Small memtable capacity (512 bytes) triggers auto-flushes concurrently with manual flushes.
        let options = EngineOptions::new(dir.path()).with_memtable_bytes(512);
        let mut engine = Engine::open(options.clone()).unwrap();

        let mut model = Model::new();
        let mut snapshots: Vec<Snapshot> = vec![engine.snapshot()];
        let mut txn_counter: u64 = 1;

        for step in steps {
            match step {
                Step::CaptureSnapshot => {
                    snapshots.push(engine.snapshot());
                }
                Step::CommitPut { snap_idx, key_idx, val } => {
                    let snap = snapshots[snap_idx % snapshots.len()];
                    let key = format!("k{}", key_idx % 4).into_bytes();
                    let row = Row::new(vec![Value::Int64(val)]);
                    let has_conflict = model.has_conflict(&key, snap.version);

                    txn_counter += 1;
                    let res = engine.commit(
                        txn_counter,
                        snap,
                        vec![Mutation::Put {
                            partition_id: 0,
                            key: key.clone(),
                            row: row.clone(),
                        }],
                    );

                    if has_conflict {
                        // Property 4: rejected commit fails with Conflict
                        prop_assert!(
                            matches!(res, Err(HtapError::Conflict(_))),
                            "expected conflict for key {:?} at snap {:?}",
                            key,
                            snap.version
                        );
                        // Property 4: rejected commit leaves no value behind
                        let cur_snap = engine.snapshot();
                        let visible = engine.get(0, &key, cur_snap).unwrap();
                        let expected = model.get_at(&key, cur_snap.version);
                        prop_assert_eq!(visible, expected, "rejected commit must leave no value behind");
                    } else {
                        let commit_v = res.expect("valid commit should succeed");
                        prop_assert_eq!(commit_v, model.visible_version.next());
                        model.apply_put(key, commit_v, row);
                        prop_assert_eq!(engine.visible_version(), model.visible_version);
                    }
                }
                Step::CommitDelete { snap_idx, key_idx } => {
                    let snap = snapshots[snap_idx % snapshots.len()];
                    let key = format!("k{}", key_idx % 4).into_bytes();
                    let has_conflict = model.has_conflict(&key, snap.version);

                    txn_counter += 1;
                    let res = engine.commit(
                        txn_counter,
                        snap,
                        vec![Mutation::Delete {
                            partition_id: 0,
                            key: key.clone(),
                        }],
                    );

                    if has_conflict {
                        prop_assert!(matches!(res, Err(HtapError::Conflict(_))));
                        let cur_snap = engine.snapshot();
                        let visible = engine.get(0, &key, cur_snap).unwrap();
                        let expected = model.get_at(&key, cur_snap.version);
                        prop_assert_eq!(visible, expected);
                    } else {
                        let commit_v = res.expect("valid delete should succeed");
                        prop_assert_eq!(commit_v, model.visible_version.next());
                        model.apply_delete(key, commit_v);
                        prop_assert_eq!(engine.visible_version(), model.visible_version);
                    }
                }
                Step::FirstWriterWinsRace { snap_idx, key_idx, val1, val2 } => {
                    let snap = snapshots[snap_idx % snapshots.len()];
                    let key = format!("k{}", key_idx % 4).into_bytes();
                    let row1 = Row::new(vec![Value::Int64(val1), Value::String("winner".into())]);
                    // Ensure val2 differs from val1 so we distinguish winner and loser
                    let val2_adj = if val1 == val2 { val1.wrapping_add(1) } else { val2 };
                    let row2 = Row::new(vec![Value::Int64(val2_adj), Value::String("loser".into())]);

                    if model.has_conflict(&key, snap.version) {
                        txn_counter += 1;
                        let res1 = engine.commit(
                            txn_counter,
                            snap,
                            vec![Mutation::Put {
                                partition_id: 0,
                                key: key.clone(),
                                row: row1,
                            }],
                        );
                        prop_assert!(matches!(res1, Err(HtapError::Conflict(_))));
                    } else {
                        // Txn 1 commits successfully
                        txn_counter += 1;
                        let commit_v1 = engine
                            .commit(
                                txn_counter,
                                snap,
                                vec![Mutation::Put {
                                    partition_id: 0,
                                    key: key.clone(),
                                    row: row1.clone(),
                                }],
                            )
                            .expect("first writer must succeed");
                        model.apply_put(key.clone(), commit_v1, row1.clone());

                        // Txn 2 tries to commit on the SAME snapshot and SAME key -> MUST fail
                        txn_counter += 1;
                        let res2 = engine.commit(
                            txn_counter,
                            snap,
                            vec![Mutation::Put {
                                partition_id: 0,
                                key: key.clone(),
                                row: row2,
                            }],
                        );
                        prop_assert!(
                            matches!(res2, Err(HtapError::Conflict(_))),
                            "Property 4: second commit on same snapshot and key must fail with Conflict"
                        );

                        // Property 4: verify rejected commit left no value behind
                        let cur_snap = engine.snapshot();
                        let visible = engine.get(0, &key, cur_snap).unwrap();
                        prop_assert_eq!(visible, Some(row1), "loser write must not overwrite winner write");
                    }
                }
                Step::PointRead { snap_idx, key_idx } => {
                    let snap = snapshots[snap_idx % snapshots.len()];
                    let key = format!("k{}", key_idx % 4).into_bytes();
                    let actual = engine.get(0, &key, snap).unwrap();
                    let expected = model.get_at(&key, snap.version);

                    // Property 1: Snapshot stability
                    prop_assert_eq!(
                        &actual,
                        &expected,
                        "Property 1: read at snap {:?} returned {:?}, expected {:?}",
                        snap.version,
                        actual,
                        expected
                    );

                    // Property 2: No future visibility
                    if let Some((entry_v, _)) = model.latest_entry_meta(&key, snap.version) {
                        prop_assert!(
                            entry_v <= snap.version,
                            "Property 2: returned version {:?} > requested snap {:?}",
                            entry_v,
                            snap.version
                        );
                    } else {
                        prop_assert_eq!(
                            &actual,
                            &None,
                            "Property 2: no entry <= snap.version, read must be None"
                        );
                    }

                    // Property 3: Delete correctness
                    if let Some((_, is_tombstone)) = model.latest_entry_meta(&key, snap.version) {
                        if is_tombstone {
                            prop_assert_eq!(
                                &actual,
                                &None,
                                "Property 3: tombstone must return None and not resurrect prior values"
                            );
                        }
                    }
                }
                Step::Flush => {
                    engine.flush().expect("flush should succeed");
                    // Property 5: Recovery equivalence: model and engine agree across all snapshots after flush
                    for s in &snapshots {
                        for k_i in 0u8..4 {
                            let k = format!("k{k_i}").into_bytes();
                            let act = engine.get(0, &k, *s).unwrap();
                            let exp = model.get_at(&k, s.version);
                            prop_assert_eq!(act, exp, "Engine and model must agree after flush at snap {:?}", s.version);
                        }
                    }
                }
                Step::Reopen => {
                    drop(engine);
                    engine = Engine::open(options.clone()).expect("Engine reopen should succeed");
                    // Property 5: Recovery equivalence across reopen
                    prop_assert_eq!(engine.visible_version(), model.visible_version);
                    for s in &snapshots {
                        for k_i in 0u8..4 {
                            let k = format!("k{k_i}").into_bytes();
                            let act = engine.get(0, &k, *s).unwrap();
                            let exp = model.get_at(&k, s.version);
                            prop_assert_eq!(act, exp, "Engine and model must agree after reopen at snap {:?}", s.version);
                        }
                    }
                }
            }
        }

        // Final verification: reopen engine from disk and check all keys across all snapshots
        drop(engine);
        let engine2 = Engine::open(options).expect("final Engine reopen must succeed");
        prop_assert_eq!(engine2.visible_version(), model.visible_version);

        for s in &snapshots {
            for k_i in 0u8..4 {
                let k = format!("k{k_i}").into_bytes();
                let act = engine2.get(0, &k, *s).unwrap();
                let exp = model.get_at(&k, s.version);
                prop_assert_eq!(act, exp, "Final reopen check failed at snap {:?}", s.version);
            }
        }

        // Verify intentionally nonexistent key
        let absent = engine2.get(0, b"k_never_written", engine2.snapshot()).unwrap();
        prop_assert_eq!(absent, None);
    }
}
