[package]
name = "htap-wire"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
htap-common = { path = "../htap-common" }
htap-server = { path = "../htap-server" }
htap-sql = { path = "../htap-sql" }
parking_lot = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
mysql = { version = "28", default-features = false, features = ["minimal-rust"] }
tempfile = { workspace = true }
