[package]
name = "htap-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
htap-catalog = { path = "../htap-catalog" }
htap-common = { path = "../htap-common" }
htap-movement = { path = "../htap-movement" }
htap-rowstore = { path = "../htap-rowstore" }
htap-sql = { path = "../htap-sql" }
htap-txn = { path = "../htap-txn" }
parking_lot = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
